blacklist = [
    "Therapist",
    "Commercial Sales Representative",
    "Financial Planning Intern",
    "Retail Sales Associate – Part Time",
    "VP of Real Estate, 2 Hour Learning (Remote) - $400,000/year USD",
    "Data Entry Assistant (100% Remote)",
    "Business Solutions Specialist",
    "Senior Software Engineer - Java Full Stack (remote)",
    "Senior Software Engineer - Java (Remote)",
    "Data Entry Clerk (100% Remote) - Entry Level",
    "Customer Support Representative (Remote)",
    "Entry Level Data Entry (Fully Remote)",
    "Entry-Level Data Entry Clerk Admin (Fully Remote)",
    "Sales And Marketing Specialist",
    "Strategic Sales Executive",
    "Part Sales Manager – Full Time",
    "Work From Home Data Entry Clerk (100% Remote)",
    "Virtual Data Entry Assistant (100% Remote)",
    "Product Manager, Marketplace Growth",
    "Entry Level Data Entry Clerk (100% Remote)",
    "Remote Data Entry Clerk - Work From Home",
    "Entry-Level Data Entry Clerk (Part-Time) Remote",
    "[Direct Sales] Account Executive",
    "Sales & Marketing Representative Inbound Final Expense Program",
    "Account Executive",
    "SVP of Real Estate Expansion, 2 Hour Learning (Remote) - $400,000/year USD",
    "Remote Travel Consultant",
    "Enterprise Account Executive",
    "Social Media Marketing Intern",
    "Product Marketing Manager",
    "Microsoft D365 ERP (F&O) + AI/Copilot Functional Consultant, Manager",
    "Bilingual Case Manager (Remote Flexible, Spanish Speaking)",
    "Sales Engineer",
    "Instructional Design Associate Manager (Remote)",
    "Accountant",
    "Graphic Design Intern",
    "Java Software Engineer",
    "Clinical Pharmacology and Pharmacometrics Intern Summer 2026",
    "Marketing Intern",
    "Product Manager",
    "Online Data Analyst Spanish Speakers (US)",
    "Part Sales Manager – Part Time",
    "Commercial Driver – Part Time",
    "Vehicle Processing Clerk (Remote - Michigan)",
    "Account Executive - Managed Services Sales",
    "Global Category Management & Procurement Analytics Intern (Remote)",
    "Licensed Mental Health Therapist - Remote",
    "Graduate Research Intern, Mathematics",
    "Econometrics Instructor (AI Training)",
    "Account Executive, LE, GBS",
    "Senior Journey Builder - SFMC & AJO",
    "Entrepreneurship Instructor (AI Training)",
    "Sales Specialist - HPE CloudOps Software Suite",
    "Frontend Engineer",
    "Product Marketing Lead - AU/US/CAN",
    "Customer Experience Specialist (CXS)",
    "Senior Technical Account Manager, Named Okta Strategic Accounts",
    "Vice President, MSP Compliance and Settlement Consulting",
    "Senior Java Software Engineer",
    "Marketing Instructor (AI Training)",
    "Senior Sales Engineer",
    "Java Developer",
    "Business Development Executive, Supply Chain, LE",
    "Regional Retirement Representative",
    "Procurement & Category Management Intern",
    "Mid-Market Account Executive - PubSec",
    "Strategic Account Executive (PAM)",
    "Customer Support Specialist, Global Payroll",
    "Senior Account Manager - Financial Services",
    "Associate Technical Account Manager",
    "Real Estate Project Management Intern (Remote)",
    "Data Engineer",
    "Senior Data Engineer",
    "Data Scientist",
    "North America Sales Manager",
    "Project Manager",
    "Customer Service Drug Program Specialist",
    "Quality Assurance Engineer",
    "Senior Manager - Corporate Tax Services",
    "Regional Sales Engineer, AIDR (Remote, East Coast)",
    "Customer Success Manager",
    "Product Owner",
    "UI Developer",
    "Customer Service Representative",
    "Digital Marketing Intern",
    "Business Development Intern",
    "Analyst I, Merchant Risk",
    "Dealer Sales Representative",
    "Senior Product Manager, Financial Reporting",
    "Inside Sales Engineer",
    "Nurse Practitioner - PRN",
    "Nurse Practitioner -PRN",
    "Content Reviewer - US",
    "Business Analyst",
    "English / Spanish Language Interpreter - Remote",
    "Executive Assistant",
    "Digital Marketing Specialist",
    "Senior Java Developer",
    "Freelance Senior Software Developer (Kotlin) - AI Trainer",
    "Sales & Business Development Intern",
    "Staff Product Designer",
    "PRN Nurse Practitioner",
    "Founding Account Executive, Investigate",
    "Retail Sales Associate – Full Time",
    "Supplier Enablement Associate",
    "Real Estate Team Lead",
    "Remote Java Engineer",
    "Java Developer (Remote)",
    "Full Stack Developer (Kotlin or Java)",
    "Backend Developer (Kotlin/Java, Android APIs)",
    "Android Software Engineer",
    "Kotlin Developer",
    "JavaScript Tutor",
    "Sales Full-Time or Part-Time",
    "Python Tutor",
    "Mobile Engineer (Kotlin/Android)",
    "Senior Ruby on Rails Developer",
    "C# Tutor",
    "Android Developer",
    "Android SDK Engineer",
    "Mobile Software Engineer",
    "Mobile Application Developer (Android)",
    "Java Tutor",
    
]
