blacklist = [
    "Therapist",
    "Commercial Sales Representative",
    "Financial Planning Intern",
    "Retail Sales Associate – Part Time",
    "VP of Real Estate, 2 Hour Learning (Remote) - $400,000/year USD",
    "Data Entry Assistant (100% Remote)",
    "Business Solutions Specialist",
    "Senior Software Engineer - Java Full Stack (remote)",
    "Senior Software Engineer - Java (Remote)",
    "Data Entry Clerk (100% Remote) - Entry Level",
    "Customer Support Representative (Remote)",
    "Entry Level Data Entry (Fully Remote)",
    "Entry-Level Data Entry Clerk Admin (Fully Remote)",
    "Sales And Marketing Specialist",
    "Strategic Sales Executive",
    "Part Sales Manager – Full Time",
    "Work From Home Data Entry Clerk (100% Remote)",
    "Virtual Data Entry Assistant (100% Remote)",
    "Product Manager, Marketplace Growth",
    "Entry Level Data Entry Clerk (100% Remote)",
    "Remote Data Entry Clerk - Work From Home",
    "Entry-Level Data Entry Clerk (Part-Time) Remote",
]
