egypt = [
    # DevOps
    {
        "role": "junior devops engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Egypt",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "devops engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Egypt",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "devops intern",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Egypt",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "graduate devops engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Egypt",
        "city": "cairo",
        "is_remote": False,
    },
    # Platform
    {
        "role": "platform engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Egypt",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "junior platform engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Egypt",
        "city": "cairo",
        "is_remote": False,
    },
    # SRE
    {
        "role": "site reliability engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Egypt",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "junior site reliability engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Egypt",
        "city": "cairo",
        "is_remote": False,
    },
    # Cloud
    {
        "role": "cloud engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Egypt",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "junior cloud engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Egypt",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "aws cloud engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Egypt",
        "city": "cairo",
        "is_remote": False,
    },
    # Infrastructure
    {
        "role": "infrastructure engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Egypt",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "cloud infrastructure engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Egypt",
        "city": "cairo",
        "is_remote": False,
    },
    # Backend
    {
        "role": "backend engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Egypt",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "junior backend engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Egypt",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "backend intern",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Egypt",
        "city": "cairo",
        "is_remote": False,
    },
    # Your strongest backend languages
    {
        "role": "golang backend engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Egypt",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "node.js backend engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Egypt",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "python backend engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Egypt",
        "city": "cairo",
        "is_remote": False,
    },
    # Other relevant early-career titles
    {
        "role": "systems engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Egypt",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "production engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Egypt",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "system admin",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Egypt",
        "city": "cairo",
        "is_remote": False,
    },
]


uae = [
    # DevOps
    {
        "role": "junior devops engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "United Arab Emirates",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "devops engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "United Arab Emirates",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "devops intern",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "United Arab Emirates",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "graduate devops engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "United Arab Emirates",
        "city": "cairo",
        "is_remote": False,
    },
    # Platform
    {
        "role": "platform engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "United Arab Emirates",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "junior platform engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "United Arab Emirates",
        "city": "cairo",
        "is_remote": False,
    },
    # SRE
    {
        "role": "site reliability engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "United Arab Emirates",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "junior site reliability engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "United Arab Emirates",
        "city": "cairo",
        "is_remote": False,
    },
    # Cloud
    {
        "role": "cloud engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "United Arab Emirates",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "junior cloud engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "United Arab Emirates",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "aws cloud engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "United Arab Emirates",
        "city": "cairo",
        "is_remote": False,
    },
    # Infrastructure
    {
        "role": "infrastructure engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "United Arab Emirates",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "cloud infrastructure engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "United Arab Emirates",
        "city": "cairo",
        "is_remote": False,
    },
    # Backend
    {
        "role": "backend engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "United Arab Emirates",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "junior backend engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "United Arab Emirates",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "backend intern",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "United Arab Emirates",
        "city": "cairo",
        "is_remote": False,
    },
    # Your strongest backend languages
    {
        "role": "golang backend engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "United Arab Emirates",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "node.js backend engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "United Arab Emirates",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "python backend engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "United Arab Emirates",
        "city": "cairo",
        "is_remote": False,
    },
    # Other relevant early-career titles
    {
        "role": "systems engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "United Arab Emirates",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "production engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "United Arab Emirates",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "system admin",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "United Arab Emirates",
        "city": "cairo",
        "is_remote": False,
    },
]


sa = [
    # DevOps
    {
        "role": "junior devops engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Saudi Arabia",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "devops engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Saudi Arabia",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "devops intern",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Saudi Arabia",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "graduate devops engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Saudi Arabia",
        "city": "cairo",
        "is_remote": False,
    },
    # Platform
    {
        "role": "platform engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Saudi Arabia",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "junior platform engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Saudi Arabia",
        "city": "cairo",
        "is_remote": False,
    },
    # SRE
    {
        "role": "site reliability engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Saudi Arabia",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "junior site reliability engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Saudi Arabia",
        "city": "cairo",
        "is_remote": False,
    },
    # Cloud
    {
        "role": "cloud engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Saudi Arabia",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "junior cloud engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Saudi Arabia",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "aws cloud engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Saudi Arabia",
        "city": "cairo",
        "is_remote": False,
    },
    # Infrastructure
    {
        "role": "infrastructure engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Saudi Arabia",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "cloud infrastructure engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Saudi Arabia",
        "city": "cairo",
        "is_remote": False,
    },
    # Backend
    {
        "role": "backend engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Saudi Arabia",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "junior backend engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Saudi Arabia",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "backend intern",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Saudi Arabia",
        "city": "cairo",
        "is_remote": False,
    },
    # Your strongest backend languages
    {
        "role": "golang backend engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Saudi Arabia",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "node.js backend engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Saudi Arabia",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "python backend engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Saudi Arabia",
        "city": "cairo",
        "is_remote": False,
    },
    # Other relevant early-career titles
    {
        "role": "systems engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Saudi Arabia",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "production engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Saudi Arabia",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "system admin",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Saudi Arabia",
        "city": "cairo",
        "is_remote": False,
    },
]


de = [
    # DevOps
    {
        "role": "junior devops engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Germany",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "devops engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Germany",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "devops intern",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Germany",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "graduate devops engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Germany",
        "city": "cairo",
        "is_remote": False,
    },
    # Platform
    {
        "role": "platform engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Germany",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "junior platform engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Germany",
        "city": "cairo",
        "is_remote": False,
    },
    # SRE
    {
        "role": "site reliability engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Germany",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "junior site reliability engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Germany",
        "city": "cairo",
        "is_remote": False,
    },
    # Cloud
    {
        "role": "cloud engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Germany",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "junior cloud engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Germany",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "aws cloud engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Germany",
        "city": "cairo",
        "is_remote": False,
    },
    # Infrastructure
    {
        "role": "infrastructure engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Germany",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "cloud infrastructure engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Germany",
        "city": "cairo",
        "is_remote": False,
    },
    # Backend
    {
        "role": "backend engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Germany",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "junior backend engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Germany",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "backend intern",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Germany",
        "city": "cairo",
        "is_remote": False,
    },
    # Your strongest backend languages
    {
        "role": "golang backend engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Germany",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "node.js backend engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Germany",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "python backend engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Germany",
        "city": "cairo",
        "is_remote": False,
    },
    # Other relevant early-career titles
    {
        "role": "systems engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Germany",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "production engineer",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Germany",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "system admin",
        "results_wanted": 999,
        "hours_old": 2.03,
        "country": "Germany",
        "city": "cairo",
        "is_remote": False,
    },
]


jobs = egypt
