jobs = [
    {
        "role": "devops",
        "results_wanted": 30,
        "hours_old": 2,
        "country": "egypt",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "backend",
        "results_wanted": 30,
        "hours_old": 2,
        "country": "egypt",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "software engineer",
        "results_wanted": 30,
        "hours_old": 2,
        "country": "egypt",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "cloud",
        "results_wanted": 30,
        "hours_old": 2,
        "country": "egypt",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "site reliability engineer",
        "results_wanted": 30,
        "hours_old": 2,
        "country": "egypt",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "sre",
        "results_wanted": 30,
        "hours_old": 2,
        "country": "egypt",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "intern",
        "results_wanted": 30,
        "hours_old": 2,
        "country": "egypt",
        "city": "cairo",
        "is_remote": False,
    },
    {
        "role": "devops",
        "results_wanted": 200,
        "hours_old": 2,
        "country": "worldwide",
        "city": "",
        "is_remote": True,
    },
    {
        "role": "backend",
        "results_wanted": 200,
        "hours_old": 2,
        "country": "worldwide",
        "city": "",
        "is_remote": True,
    },
    {
        "role": "software engineer",
        "results_wanted": 200,
        "hours_old": 2,
        "country": "worldwide",
        "city": "",
        "is_remote": True,
    },
    {
        "role": "intern",
        "results_wanted": 200,
        "hours_old": 2,
        "country": "worldwide",
        "city": "",
        "is_remote": True,
    },
]
