name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5.0.0
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ahmedhesham301/jobfitai:$(date +%s)

    - name: login to dockerhub
      uses: docker/login-action@v3.6.0
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    
