name: Docker Image CI

on:
  push:
    paths: 
      - '**'
      - '!.github/workflows/**'
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v5.0.0

    - name: login to dockerhub
      uses: docker/login-action@v3.6.0
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ahmedhesham301/jobfit-ai:latest