name: Run Docker Image

on:
  workflow_dispatch:  # run manually, or change to push/pr

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Docker container with secrets
      run: |
        docker run \
          -e smtp_email=${{ secrets.SMTP_EMAIL }} \
          -e smtp_password=${{ secrets.SMTP_PASSWORD }} \
          -e receiver_email=${{ secrets.RECEIVER_EMAIL }} \
          -e api_keys=${{ secrets.API_KEYS }} \
          ahmedhesham301/jobfit-ai:latest
