name: Run Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *" 

jobs:
  run-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Run container
        run: |
          docker run ahmedhesham301/jobfit-ai:latest
